enum SaveExceptions { FILE_ALREADY_EXISTS, YOU_CAN_SAVE }

enum Auth_Exceptions {
  EMAIL_ALREADY_EXISTS,
  NETWORK_ERROR,
  INVALID_EMAIL,
  REGISTRATION_SUCCESS,
  EMAIL_NOT_VERIFIED,
  LOGIN_SUCCESSFULL,
  ACCOUNT_NOT_FOUND,
  INVALID_PASSWORD,
  RESET_LINK_SENT,
}
